"""empty message

Revision ID: 1e6313192d7b
Revises: 412c6eb48725
Create Date: 2016-11-17 15:32:09.317837

"""

# revision identifiers, used by Alembic.
revision = '1e6313192d7b'
down_revision = '412c6eb48725'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_timestamp', 'answers', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_timestamp', 'answers')
    op.drop_table('answers')
    ### end Alembic commands ###
