"""empty message

Revision ID: 2df0de34f706
Revises: 54371ce57065
Create Date: 2016-11-16 16:53:43.587640

"""

# revision identifiers, used by Alembic.
revision = '2df0de34f706'
down_revision = '54371ce57065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
