"""empty message

Revision ID: 358d591f4bde
Revises: None
Create Date: 2016-11-07 21:31:25.142489

"""

# revision identifiers, used by Alembic.
revision = '358d591f4bde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
