"""empty message

Revision ID: 36ff037f7e24
Revises: 1e6313192d7b
Create Date: 2016-11-17 15:49:12.180125

"""

# revision identifiers, used by Alembic.
revision = '36ff037f7e24'
down_revision = '1e6313192d7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
