"""empty message

Revision ID: 3720914dab80
Revises: 2df0de34f706
Create Date: 2016-11-16 16:54:26.987824

"""

# revision identifiers, used by Alembic.
revision = '3720914dab80'
down_revision = '2df0de34f706'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
