"""empty message

Revision ID: 51b91ea44490
Revises: 3720914dab80
Create Date: 2016-11-16 17:46:55.058909

"""

# revision identifiers, used by Alembic.
revision = '51b91ea44490'
down_revision = '3720914dab80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
