"""empty message

Revision ID: 54371ce57065
Revises: 49dd40fa8d1b
Create Date: 2016-11-15 20:42:12.385918

"""

# revision identifiers, used by Alembic.
revision = '54371ce57065'
down_revision = '49dd40fa8d1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
